# Generated by Django 4.1.3 on 2024-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OVA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images\\profile\\default.png', upload_to='images'),
        ),
    ]
